/**
 * Client-side identity store.
 *
 * Loads user-to-participant mappings from a static JSON file (identity.json)
 * generated by the seed script. This replaces the VCP's /users endpoints —
 * the VCP never stores PII or cross-assembly identity links.
 */

export interface IdentityUser {
  id: string;
  name: string;
  memberships: IdentityMembership[];
}

export interface IdentityMembership {
  assemblyId: string;
  assemblyName: string;
  participantId: string;
}

export interface IdentityStore {
  listUsers(): IdentityUser[];
  getUserMemberships(userId: string): IdentityMembership[];
  getParticipantId(userId: string, assemblyId: string): string | null;
}

interface IdentityData {
  users: IdentityUser[];
}

let cached: IdentityStore | null = null;

export async function loadIdentityStore(): Promise<IdentityStore> {
  if (cached) return cached;

  const res = await fetch("/identity.json");
  if (!res.ok) {
    console.warn("[identity-store] Failed to load identity.json:", res.status);
    cached = createEmptyStore();
    return cached;
  }

  const data: IdentityData = await res.json();
  const userMap = new Map(data.users.map((u) => [u.id, u]));

  cached = {
    listUsers: () => data.users,
    getUserMemberships: (userId) => userMap.get(userId)?.memberships ?? [],
    getParticipantId: (userId, assemblyId) => {
      const user = userMap.get(userId);
      if (!user) return null;
      return user.memberships.find((m) => m.assemblyId === assemblyId)?.participantId ?? null;
    },
  };

  return cached;
}

function createEmptyStore(): IdentityStore {
  return {
    listUsers: () => [],
    getUserMemberships: () => [],
    getParticipantId: () => null,
  };
}

/** Reset cache — used when the seed script regenerates identity.json. */
export function resetIdentityStore(): void {
  cached = null;
}
